// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://talkygolchivffiftkso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbGt5Z29sY2hpdmZmaWZ0a3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODEyNTMsImV4cCI6MjA2ODU1NzI1M30.00bWDHsdXUh4_ck-Dh-_pafpNJpv088y8S3fniwMAo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});